module.exports = {
  DocsSidebar: [
    {
      type: 'category',
      label: 'Solidity入门指南',
      collapsible: true,
      items: [
        'intro',
        'install-remix',
        'hello-world',
        'contract-building-block',
        'comment',
        'data-types',
        'bool',
        'integer',
        'address',
        'static-byte-array',
        'dynamic-byte-array',
        'literal',
        'enum',
        'user-defined-types',
        'data-location',
        'array',
        'array-slice',
        'array-members',
        'array-multi-dimension',
        'if-else',
        'for',
        'while',
        'do-while',
        'break',
      ],
    },
  ],
};
