module.exports = {
  DocsSidebar: [
    {
      type: 'category',
      label: 'Solidity入门简介',
      collapsible: false,
      items: [
        'intro',
        'install-remix',
        'hello-world',
        'contract-building-block',
        'comment',
      ],
    },
    {
      type: 'category',
      label: 'Solidity数据类型',
      collapsible: false,
      items: [
        'data-types',
        'bool',
        'integer',
        'address',
        'static-byte-array',
        'literal',
        'enum',
        'user-defined-types',
        'data-location',
        'array',
        'array-slice',
        'array-members',
        'array-multi-dimension',
        'dynamic-byte-array',
        'struct',
        'mapping',
      ],
    },
    {
      type: 'category',
      label: 'Solidity控制结构',
      collapsible: false,
      items: [
        'if-else',
        'for',
        'while',
        'do-while',
        'break',
        'continue',
        'require',
        'assert',
        'revert',
      ],
    },
  ],
};
